functionsDirectory = "C:\\Users\\jamju\\OneDrive\\Desktop\\Claude code\\EventCalc Pro v7\\files\\netlify\\functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\jamju\\OneDrive\\Desktop\\Claude code\\EventCalc Pro v7\\files"
publishOrigin = "default"
functions = "C:\\Users\\jamju\\OneDrive\\Desktop\\Claude code\\EventCalc Pro v7\\files\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]